export interface NotificationTheme {
  id: string;
  label: string;
  emoji: string;
  /** CSS gradient for the card background */
  gradient: string;
  /** Primary accent colour (hex) */
  accent: string;
  /** Floating particle emojis shown in animated preview */
  particles: string[];
  /** Short description shown on the card */
  description: string;
  /** Email header background gradient (inline CSS) */
  emailGradient: string;
  /** Email header text colour */
  emailHeaderColor: string;
  /** Default subject line suggested when selecting this theme */
  defaultTitle: string;
  /** Default body message suggested when selecting this theme */
  defaultBody: string;
}

export const NOTIFICATION_THEMES: NotificationTheme[] = [
  {
    id: 'birthday',
    label: 'Birthday',
    emoji: '🎂',
    gradient: 'linear-gradient(135deg,#7c3aed 0%,#db2777 100%)',
    accent: '#7c3aed',
    particles: ['🎂', '🎈', '🎉', '🥳', '🎁', '✨'],
    description: 'Celebrate their special day',
    emailGradient: 'linear-gradient(135deg,#7c3aed,#db2777)',
    emailHeaderColor: '#ffffff',
    defaultTitle: 'Happy Birthday, {firstName}! 🎂',
    defaultBody: 'Wishing you a wonderful birthday filled with happiness, health, and great strength! 🎈 May this year bring you closer to all your fitness dreams. Enjoy your special day from all of us!',
  },
  {
    id: 'celebration',
    label: 'Celebration',
    emoji: '🎉',
    gradient: 'linear-gradient(135deg,#d97706 0%,#dc2626 100%)',
    accent: '#d97706',
    particles: ['🎉', '🎊', '🥂', '✨', '🌟', '🎆'],
    description: 'For exciting announcements',
    emailGradient: 'linear-gradient(135deg,#d97706,#dc2626)',
    emailHeaderColor: '#ffffff',
    defaultTitle: 'Celebrating Big Achievements! 🎉',
    defaultBody: 'We love celebrating wins! Hi {firstName}, congratulations on reaching this milestone. Your consistency and dedication inspire everyone around you. Keep shining! ✨',
  },
  {
    id: 'diwali',
    label: 'Diwali',
    emoji: '🪔',
    gradient: 'linear-gradient(135deg,#f97316 0%,#eab308 100%)',
    accent: '#f97316',
    particles: ['🪔', '✨', '🌟', '🎆', '🎇', '💛'],
    description: 'Festival of lights greetings',
    emailGradient: 'linear-gradient(135deg,#7c2d12,#ea580c)',
    emailHeaderColor: '#fef08a',
    defaultTitle: 'Happy Diwali to You and Your Family! 🪔',
    defaultBody: 'Warmest Diwali wishes to you and your loved ones! 🪔 May this festival of lights illuminate your life with good health, immense happiness, and boundless strength. Have a blessed and joyful celebration!',
  },
  {
    id: 'sankranti',
    label: 'Sankranti',
    emoji: '🪁',
    gradient: 'linear-gradient(135deg,#ea580c 0%,#16a34a 100%)',
    accent: '#ea580c',
    particles: ['🪁', '☀️', '🌾', '🌿', '🎋', '💚'],
    description: 'Harvest festival wishes',
    emailGradient: 'linear-gradient(135deg,#7c2d12,#15803d)',
    emailHeaderColor: '#fef9c3',
    defaultTitle: 'Happy Makar Sankranti! 🪁',
    defaultBody: 'Wishing you a joyful and prosperous Makar Sankranti! 🪁 May your spirits soar as high as the kites in the sky, and may this harvest season bring abundant health, energy, and joy to your life!',
  },
  {
    id: 'ganesh',
    label: 'Ganesh Festival',
    emoji: '🐘',
    gradient: 'linear-gradient(135deg,#c2410c 0%,#fbbf24 100%)',
    accent: '#c2410c',
    particles: ['🐘', '🌺', '✨', '🪔', '🌸', '🎊'],
    description: 'Ganpati Bappa Morya!',
    emailGradient: 'linear-gradient(135deg,#7c2d12,#b45309)',
    emailHeaderColor: '#fef3c7',
    defaultTitle: 'Happy Ganesh Chaturthi! 🐘 Ganpati Bappa Morya!',
    defaultBody: 'May Lord Ganesha remove all obstacles from your path and bless you with vibrant health, peace, and enduring strength. Wishing you and your family a blessed Ganesh Festival! 🌺',
  },
  {
    id: 'eid',
    label: 'Eid',
    emoji: '🌙',
    gradient: 'linear-gradient(135deg,#15803d 0%,#ca8a04 100%)',
    accent: '#15803d',
    particles: ['🌙', '⭐', '✨', '🕌', '🌟', '💚'],
    description: 'Eid Mubarak greetings',
    emailGradient: 'linear-gradient(135deg,#14532d,#713f12)',
    emailHeaderColor: '#fef9c3',
    defaultTitle: 'Eid Mubarak to You and Your Family! 🌙',
    defaultBody: 'Eid Mubarak! 🌙 Wishing you peace, prosperity, and joy on this special occasion. May this blessed day bring countless blessings and good health to you and your loved ones.',
  },
  {
    id: 'christmas',
    label: 'Christmas',
    emoji: '🎄',
    gradient: 'linear-gradient(135deg,#dc2626 0%,#16a34a 100%)',
    accent: '#dc2626',
    particles: ['🎄', '❄️', '⛄', '🎁', '🌟', '✨'],
    description: "Season's greetings",
    emailGradient: 'linear-gradient(135deg,#7f1d1d,#14532d)',
    emailHeaderColor: '#fef3c7',
    defaultTitle: 'Merry Christmas & Happy Holidays! 🎄',
    defaultBody: 'Wishing you a Merry Christmas filled with warmth, laughter, and cheer! 🎁 May the holiday season bring you rejuvenation, joy, and peace as you prepare for another powerful year!',
  },
  {
    id: 'newyear',
    label: 'New Year',
    emoji: '🎆',
    gradient: 'linear-gradient(135deg,#1e1b4b 0%,#ca8a04 100%)',
    accent: '#ca8a04',
    particles: ['🎆', '🥂', '🎊', '✨', '🌟', '🎇'],
    description: 'Happy New Year wishes',
    emailGradient: 'linear-gradient(135deg,#1e1b4b,#3730a3)',
    emailHeaderColor: '#fef9c3',
    defaultTitle: 'Happy New Year, {firstName}! 🎆 Ready for New Heights?',
    defaultBody: 'Happy New Year! 🎆 A fresh year, fresh goals, and endless possibilities. Let’s make this year your strongest, fittest, and healthiest one yet. We can’t wait to see what you achieve!',
  },
  {
    id: 'motivation',
    label: 'Motivation',
    emoji: '🔥',
    gradient: 'linear-gradient(135deg,#dc2626 0%,#f97316 100%)',
    accent: '#dc2626',
    particles: ['🔥', '💪', '⚡', '🎯', '🏋️', '💥'],
    description: 'Fire up your members',
    emailGradient: 'linear-gradient(135deg,#7f1d1d,#c2410c)',
    emailHeaderColor: '#fef3c7',
    defaultTitle: 'Push Your Limits Today, {firstName}! 🔥',
    defaultBody: 'Remember why you started! Hi {firstName}, every single workout brings you one step closer to your best self. Sweat today, conquer tomorrow. See you on the gym floor! 💪',
  },
  {
    id: 'fitness',
    label: 'Fitness Goal',
    emoji: '💪',
    gradient: 'linear-gradient(135deg,#1d4ed8 0%,#0891b2 100%)',
    accent: '#1d4ed8',
    particles: ['💪', '🏃', '⚡', '🎯', '🏋️', '🥇'],
    description: 'Push for new PRs',
    emailGradient: 'linear-gradient(135deg,#1e3a8a,#0e7490)',
    emailHeaderColor: '#e0f2fe',
    defaultTitle: 'New Fitness Goal Unlocked! 💪',
    defaultBody: 'Your hard work is paying off! Hi {firstName}, stay dialed into your routine. Remember to stay hydrated, hit your protein goals, and celebrate every single PR. Let’s keep moving forward!',
  },
  {
    id: 'fee_reminder',
    label: 'Fee Reminder',
    emoji: '💰',
    gradient: 'linear-gradient(135deg,#d97706 0%,#ca8a04 100%)',
    accent: '#d97706',
    particles: ['💰', '📅', '⏰', '🔔', '💳', '📋'],
    description: 'Membership payment due',
    emailGradient: 'linear-gradient(135deg,#78350f,#92400e)',
    emailHeaderColor: '#fef3c7',
    defaultTitle: 'Membership Fee Reminder 💰',
    defaultBody: 'Hi {firstName}, your {plan} membership fee of {amount} is due on {dueDate}. Please complete the renewal at reception or online to continue uninterrupted workouts!',
  },
  {
    id: 'overdue',
    label: 'Overdue Alert',
    emoji: '⚠️',
    gradient: 'linear-gradient(135deg,#dc2626 0%,#be185d 100%)',
    accent: '#dc2626',
    particles: ['⚠️', '🔴', '📅', '⏰', '🔔', '❗'],
    description: 'Urgent payment overdue',
    emailGradient: 'linear-gradient(135deg,#7f1d1d,#831843)',
    emailHeaderColor: '#fecdd3',
    defaultTitle: 'Urgent: Overdue Membership Notice ⚠️',
    defaultBody: 'Hi {firstName}, your {plan} membership renewal is currently overdue. Please contact reception today to settle the pending dues and reactivate your gym access.',
  },
  {
    id: 'achievement',
    label: 'Achievement',
    emoji: '🌟',
    gradient: 'linear-gradient(135deg,#ca8a04 0%,#d97706 100%)',
    accent: '#ca8a04',
    particles: ['🌟', '🏆', '🥇', '✨', '🎖️', '👑'],
    description: 'Celebrate milestones',
    emailGradient: 'linear-gradient(135deg,#713f12,#92400e)',
    emailHeaderColor: '#fef9c3',
    defaultTitle: 'New Milestone Reached! 🌟',
    defaultBody: 'Huge congratulations to {name}! 🌟 Your hard work, discipline, and dedication have paid off. We are incredibly proud of your journey and excited to see your next PR!',
  },
  {
    id: 'gym_update',
    label: 'Gym Update',
    emoji: '📣',
    gradient: 'linear-gradient(135deg,#2563eb 0%,#7c3aed 100%)',
    accent: '#2563eb',
    particles: ['📣', '📢', '🔔', '💬', '📋', '✅'],
    description: 'General announcements',
    emailGradient: 'linear-gradient(135deg,#1e3a8a,#4c1d95)',
    emailHeaderColor: '#e0e7ff',
    defaultTitle: 'Important Gym Announcement 📣',
    defaultBody: 'Hi {firstName}, we have an important update regarding our gym schedules and facilities. Please check out the details and reach out to our team if you have any questions!',
  },
  {
    id: 'welcome',
    label: 'Welcome',
    emoji: '❤️',
    gradient: 'linear-gradient(135deg,#0d9488 0%,#16a34a 100%)',
    accent: '#0d9488',
    particles: ['❤️', '🤝', '✨', '🌟', '😊', '🏠'],
    description: 'Greet new members',
    emailGradient: 'linear-gradient(135deg,#134e4a,#14532d)',
    emailHeaderColor: '#ccfbf1',
    defaultTitle: 'Welcome to the Gym Family, {firstName}! ❤️',
    defaultBody: 'We are thrilled to welcome you, {name}! 🎉 Your fitness journey starts now. Our trainers and staff are here to support you at every rep, set, and milestone. Let’s crush it together!',
  },
  {
    id: 'miss_you',
    label: 'We Miss You',
    emoji: '😢',
    gradient: 'linear-gradient(135deg,#4338ca 0%,#7c3aed 100%)',
    accent: '#4338ca',
    particles: ['😢', '💙', '🤗', '🙏', '👋', '💌'],
    description: 'Re-engage inactive members',
    emailGradient: 'linear-gradient(135deg,#1e1b4b,#4c1d95)',
    emailHeaderColor: '#e0e7ff',
    defaultTitle: 'We Miss You at the Gym, {firstName}! 😢',
    defaultBody: "Hi {firstName}, we noticed you haven't checked in lately. Life gets busy, but your health comes first! Come in for a quick session this week — your gym family is waiting for you! 💙",
  },
  {
    id: 'challenge',
    label: 'Challenge',
    emoji: '🏆',
    gradient: 'linear-gradient(135deg,#ea580c 0%,#ca8a04 100%)',
    accent: '#ea580c',
    particles: ['🏆', '⚡', '🔥', '💪', '🎯', '🥊'],
    description: 'Launch a fitness challenge',
    emailGradient: 'linear-gradient(135deg,#7c2d12,#713f12)',
    emailHeaderColor: '#fef3c7',
    defaultTitle: '30-Day Fitness Challenge Announced! 🏆',
    defaultBody: "Are you ready to test your grit? 🏆 We're kicking off an exciting gym-wide fitness challenge! Sign up at reception or talk to a trainer to participate and win exciting prizes!",
  },
  {
    id: 'holi',
    label: 'Holi',
    emoji: '🌸',
    gradient: 'linear-gradient(135deg,#ec4899 0%,#f97316 50%,#8b5cf6 100%)',
    accent: '#ec4899',
    particles: ['🌸', '🎨', '🌈', '✨', '💜', '🌺'],
    description: 'Happy Holi splash!',
    emailGradient: 'linear-gradient(135deg,#831843,#7c2d12)',
    emailHeaderColor: '#fdf4ff',
    defaultTitle: 'Happy Holi! Wishing You Vibrant Colors & Health! 🌸',
    defaultBody: 'Wishing you a joyous and colorful Holi! 🌸🎨 May your life be filled with vibrant happiness, radiant health, and boundless energy. Have a safe and joyful celebration with family and friends!',
  },
  {
    id: 'milestone',
    label: 'Milestone',
    emoji: '🎓',
    gradient: 'linear-gradient(135deg,#1e3a8a 0%,#ca8a04 100%)',
    accent: '#1e3a8a',
    particles: ['🎓', '🏅', '🌟', '✨', '👏', '🥳'],
    description: 'Long-term member rewards',
    emailGradient: 'linear-gradient(135deg,#1e3a8a,#713f12)',
    emailHeaderColor: '#fef9c3',
    defaultTitle: 'Celebrating Your Fitness Anniversary! 🎓',
    defaultBody: 'Hi {firstName}, congratulations on another year of dedicated training with us! 🌟 Your commitment inspires everyone in our community. Thank you for being a valued member of our family!',
  },
  {
    id: 'wellness',
    label: 'Wellness',
    emoji: '🧘',
    gradient: 'linear-gradient(135deg,#4ade80 0%,#2dd4bf 100%)',
    accent: '#16a34a',
    particles: ['🧘', '🌿', '💚', '🌱', '🌸', '☮️'],
    description: 'Mind & body balance',
    emailGradient: 'linear-gradient(135deg,#14532d,#134e4a)',
    emailHeaderColor: '#dcfce7',
    defaultTitle: 'Prioritize Your Recovery & Mind-Body Balance 🧘',
    defaultBody: 'Hi {firstName}, rest and recovery are just as crucial as the grind. Remember to stretch, stay hydrated, prioritize quality sleep, and nourish your body. Here’s to your complete wellness! 🌿',
  },
];

export const DEFAULT_THEME_ID = 'gym_update';

export function getTheme(id: string | null | undefined): NotificationTheme | undefined {
  return NOTIFICATION_THEMES.find((t) => t.id === id);
}
